import YahooFinance from 'yahoo-finance2';

const yahooFinance = new YahooFinance({ suppressNotices: ['yahooSurvey'] });
const QUOTE_CACHE_TTL = 9000;
const quoteCache = new Map();
let batchInFlight = null;

function timeout(promise, ms = 12000) {
  return Promise.race([
    promise,
    new Promise((_, reject) => setTimeout(() => reject(new Error('انتهت مهلة مصدر البيانات')), ms))
  ]);
}
function finiteNumber(value){if(value===null||value===undefined||value==='')return null;const n=Number(value);return Number.isFinite(n)?n:null}
function positiveNumber(value){const n=finiteNumber(value);return n!=null&&n>0?n:null}
function quoteTime(value){if(!value)return null;if(value instanceof Date&&!Number.isNaN(value.getTime()))return value.toISOString();const n=Number(value);if(Number.isFinite(n)){const d=new Date(n>1e12?n:n*1000);if(!Number.isNaN(d.getTime()))return d.toISOString()}const d=new Date(value);return Number.isNaN(d.getTime())?null:d.toISOString()}
function newYorkClock(date=new Date()){const v=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',weekday:'short',hour12:false}).formatToParts(date).reduce((a,p)=>({...a,[p.type]:p.value}),{});const hour=Number(v.hour)%24,minute=Number(v.minute);return{date:`${v.year}-${v.month}-${v.day}`,weekday:v.weekday,minutes:hour*60+minute}}
function clockSession(date=new Date()){const c=newYorkClock(date);if(['Sat','Sun'].includes(c.weekday))return{...c,session:'CLOSED'};if(c.minutes>=240&&c.minutes<570)return{...c,session:'PRE_MARKET'};if(c.minutes>=570&&c.minutes<960)return{...c,session:'REGULAR'};if(c.minutes>=960&&c.minutes<1200)return{...c,session:'POST_MARKET'};return{...c,session:'CLOSED'}}
function timestampMatchesNewYorkDate(ts,expected){if(!ts)return false;const d=new Date(ts);return !Number.isNaN(d.getTime())&&newYorkClock(d).date===expected}
function derivedChange(price,baseline,suppliedChange,suppliedPercent){const dc=finiteNumber(suppliedChange),dp=finiteNumber(suppliedPercent),ref=positiveNumber(baseline);return{change:dc??(price!=null&&ref!=null?price-ref:null),changePercent:dp??(price!=null&&ref!=null?((price/ref)-1)*100:null)}}
function selectSessionQuote(q){const raw=String(q.marketState||'UNKNOWN').toUpperCase(),clock=clockSession(),regular=positiveNumber(q.regularMarketPrice),pre=positiveNumber(q.preMarketPrice),post=positiveNumber(q.postMarketPrice),prev=positiveNumber(q.regularMarketPreviousClose),rt=quoteTime(q.regularMarketTime),prt=quoteTime(q.preMarketTime),pot=quoteTime(q.postMarketTime),currentPre=pre!=null&&timestampMatchesNewYorkDate(prt,clock.date),currentPost=post!=null&&timestampMatchesNewYorkDate(pot,clock.date);if(currentPre&&(clock.session==='PRE_MARKET'||['PRE','PREPRE'].includes(raw))){return{price:pre,...derivedChange(pre,prev,q.preMarketChange,q.preMarketChangePercent),session:'PRE_MARKET',sessionLabel:'ما قبل الافتتاح',updatedAt:prt,source:'Yahoo Finance • Batched Pre-Market',isExtendedHours:true,isLiveSession:true,isFresh:true}}if(currentPost&&(clock.session==='POST_MARKET'||['POST','POSTPOST'].includes(raw))){return{price:post,...derivedChange(post,regular,q.postMarketChange,q.postMarketChangePercent),session:'POST_MARKET',sessionLabel:'ما بعد الإغلاق',updatedAt:pot,source:'Yahoo Finance • Batched After-Hours',isExtendedHours:true,isLiveSession:true,isFresh:true}}const regularOpen=clock.session==='REGULAR'&&raw==='REGULAR';return{price:regular,...derivedChange(regular,prev,q.regularMarketChange,q.regularMarketChangePercent),session:regularOpen?'REGULAR':'REGULAR_CLOSE',sessionLabel:regularOpen?'الجلسة النظامية':'آخر إغلاق',updatedAt:rt,source:regularOpen?'Yahoo Finance • Batched Regular Session':'Yahoo Finance • Cached Last Regular Close',isExtendedHours:false,isLiveSession:regularOpen,isFresh:regularOpen&&timestampMatchesNewYorkDate(rt,clock.date)}}
function normalizeQuote(q){const s=selectSessionQuote(q);return{symbol:q.symbol,name:q.shortName||q.longName||q.symbol,price:s.price,change:s.change,changePercent:s.changePercent,open:q.regularMarketOpen??null,high:q.regularMarketDayHigh??null,low:q.regularMarketDayLow??null,previousClose:q.regularMarketPreviousClose??null,fiftyTwoWeekHigh:q.fiftyTwoWeekHigh??null,fiftyTwoWeekLow:q.fiftyTwoWeekLow??null,volume:q.regularMarketVolume??null,averageVolume:q.averageDailyVolume3Month??q.averageDailyVolume10Day??null,marketState:q.marketState??'UNKNOWN',session:s.session,sessionLabel:s.sessionLabel,isExtendedHours:s.isExtendedHours,isLiveSession:s.isLiveSession,isFresh:s.isFresh,regularMarketPrice:q.regularMarketPrice??null,preMarketPrice:q.preMarketPrice??null,postMarketPrice:q.postMarketPrice??null,currency:q.currency??'USD',exchange:q.fullExchangeName??q.exchange??'',updatedAt:s.updatedAt,observedAt:new Date().toISOString(),source:s.source}}

export async function getQuotes(symbols){const clean=[...new Set((symbols||[]).map(s=>String(s||'').trim().toUpperCase()).filter(Boolean))];if(!clean.length)return[];const now=Date.now();const fresh=[],missing=[];for(const s of clean){const c=quoteCache.get(s);if(c&&now-c.at<QUOTE_CACHE_TTL)fresh.push(c.value);else missing.push(s)}if(missing.length){if(batchInFlight)await batchInFlight.catch(()=>{});batchInFlight=(async()=>{const raw=await timeout(yahooFinance.quote(missing));const arr=Array.isArray(raw)?raw:[raw];for(const q of arr){if(!q?.symbol)continue;const n=normalizeQuote(q);quoteCache.set(String(q.symbol).toUpperCase(),{at:Date.now(),value:n})}})();try{await batchInFlight}finally{batchInFlight=null}}return clean.map(s=>quoteCache.get(s)?.value).filter(Boolean)}
export async function getQuote(symbol){const rows=await getQuotes([symbol]);if(!rows[0])throw new Error('تعذر جلب السعر');return rows[0]}

export async function getHistory(symbol,period1,period2=new Date(),interval='1d'){const result=await timeout(yahooFinance.chart(symbol,{period1,period2,interval,events:'div|split'}),18000);return(result.quotes||[]).filter(x=>x.close!=null).map(x=>({date:x.date,open:x.open,high:x.high,low:x.low,close:x.close,adjclose:x.adjclose,volume:x.volume}))}
export async function searchUsEquities(query,count=12){const q=String(query||'').trim();if(!q)return[];const result=await timeout(yahooFinance.search(q,{quotesCount:Math.min(25,Math.max(1,count)),newsCount:0}),12000);const allowed=new Set(['NMS','NGM','NCM','NYQ','ASE','PCX','BTS']);return(result.quotes||[]).filter(x=>x&&x.symbol&&(x.quoteType==='EQUITY'||x.typeDisp==='Equity')).filter(x=>!x.exchange||allowed.has(x.exchange)).map(x=>({symbol:x.symbol,name:x.shortname||x.longname||x.symbol,exchange:x.exchDisp||x.exchange||'',sector:x.sector||'',industry:x.industry||''}))}
export async function getMarketPulse(){const defs=[['^GSPC','S&P 500'],['^IXIC','Nasdaq'],['^DJI','Dow Jones'],['^RUT','Russell 2000'],['^VIX','VIX']];let rows=[];try{const q=await getQuotes(defs.map(x=>x[0]));const m=new Map(q.map(x=>[x.symbol,x]));rows=defs.map(([symbol,label])=>m.has(symbol)?{label,...m.get(symbol)}:{symbol,label,error:'تعذر جلب المؤشر'})}catch(e){rows=defs.map(([symbol,label])=>({symbol,label,error:e.message}))}const tradable=rows.filter(x=>Number.isFinite(x.changePercent)&&x.symbol!=='^VIX'),avg=tradable.length?tradable.reduce((a,x)=>a+x.changePercent,0)/tradable.length:null,vix=rows.find(x=>x.symbol==='^VIX')?.price;let score=50;if(avg!=null)score+=Math.max(-25,Math.min(25,avg*12));if(Number.isFinite(vix))score+=vix<18?12:vix<24?2:vix<30?-12:-22;score=Math.round(Math.max(0,Math.min(100,score)));return{rows,score,regime:score>=70?'إيجابي':score>=45?'حذر':'دفاعي',updatedAt:new Date().toISOString()}}
