const Q=(s)=>document.querySelector(s);const F=(v,d=2)=>Number.isFinite(Number(v))?Number(v).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d}):'—';
let sb=null,session=null;
async function initClient(){const c=await fetch('/api/config',{cache:'no-store'}).then(r=>r.json());if(!c?.supabase?.enabled||!window.supabase)return null;sb=window.supabase.createClient(c.supabase.url,c.supabase.publishableKey);session=(await sb.auth.getSession()).data.session;return session;}
async function loadPortfolioData(){if(!session)return null;const uid=session.user.id;const [p,t,a,r]=await Promise.all([
 sb.from('portfolio').select('*').eq('user_id',uid).order('created_at',{ascending:true}),
 sb.from('trades').select('*').eq('user_id',uid).order('created_at',{ascending:false}).limit(20),
 sb.from('portfolio_adjustments').select('*').eq('user_id',uid).order('created_at',{ascending:false}).limit(20),
 sb.from('portfolio_reconciliations').select('*').eq('user_id',uid).order('reconciled_at',{ascending:false}).limit(1)
]);if(p.error)throw p.error;const positions=p.data||[];const analysis=positions.length?await fetch('/api/portfolio-analysis',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({positions})}).then(x=>x.json()):[];return{positions,analysis,trades:t.data||[],adjustments:a.data||[],reconciliation:r.data?.[0]||null};}
function syncView(d){const expected=['AMPL','CRDL'];const actual=d.positions.map(x=>x.symbol).sort();const ok=actual.length===expected.length&&expected.every(x=>actual.includes(x));const el=Q('#portfolioSyncStrip');if(!el)return;el.classList.toggle('bad',!ok);el.innerHTML=`<div><b>${ok?'✅ المحفظة متطابقة':'⚠️ اختلاف في المحفظة'}</b><small>${ok?'AMPL وCRDL فقط':'المراكز الحالية: '+(actual.join(', ')||'لا توجد')}</small></div><div class="sync-meta"><div><span>عدد المراكز</span><b>${actual.length}</b></div><div><span>آخر تحديث</span><b>${new Date().toLocaleTimeString('ar-SA')}</b></div><div><span>المصدر</span><b>Supabase</b></div></div>`;}
function riskView(d){const rows=d.analysis||[];const total=rows.reduce((s,x)=>s+Number(x.analysis?.marketValue||0),0);let atRisk=0,closest=null;for(const x of rows){const q=Number(x.position?.quantity||0),price=Number(x.price||0),stop=Number(x.position?.stopLoss||0);if(stop>0){const risk=Math.max(0,(price-stop)*q);atRisk+=risk;const dist=((price/stop)-1)*100;if(!closest||dist<closest.dist)closest={symbol:x.symbol,dist};}}const maxPosition=total?Math.max(...rows.map(x=>Number(x.analysis?.marketValue||0)/total*100)):0;const level=atRisk>total*.08||maxPosition>80?'مرتفعة':atRisk>total*.04||maxPosition>60?'متوسطة':'منخفضة';Q('#riskLevel').textContent=level;Q('#riskExposure').textContent=`$${F(atRisk)}`;Q('#riskConcentration').textContent=`${F(maxPosition,1)}%`;Q('#riskClosestStop').textContent=closest?`${closest.symbol} · ${F(closest.dist,1)}%`:'لا يوجد وقف';}
function nowView(d){const rows=d.analysis||[];const actions=[];for(const x of rows){const s=Number(x.analysis?.asiriScore||0),p=Number(x.analysis?.pnlPct||0);if(x.symbol==='AMPL')actions.push(s>=70?'احتفظ بـ AMPL وراقب رفع الوقف':'راقب AMPL دون تعزيز');else if(x.symbol==='CRDL')actions.push(!x.position?.stopLoss?'سجّل وقف خسارة لـ CRDL':s>=65?'احتفظ بـ CRDL مع الالتزام بالوقف':'راقب CRDL بحذر');if(p<-8)actions.push(`مراجعة عاجلة لخسارة ${x.symbol}`);}Q('#whatNowResult').innerHTML=actions.length?actions.map(x=>`<p>• ${x}</p>`).join(''):'<p>لا توجد بيانات كافية.</p>';}
function historyView(d){const rows=[...d.trades.map(x=>({at:x.created_at,text:`${x.symbol} · ${x.action} · ${F(x.quantity,2)} سهم`})),...d.adjustments.map(x=>({at:x.created_at,text:`${x.symbol} · تعديل إداري للكمية أو المتوسط`}))].sort((a,b)=>new Date(b.at)-new Date(a.at)).slice(0,12);Q('#portfolioHistory').innerHTML=rows.length?rows.map(x=>`<div class="history-item"><b>${x.text}</b><small>${new Date(x.at).toLocaleString('ar-SA')}</small></div>`).join(''):'<p class="muted">لا توجد تحديثات مسجلة.</p>';}
async function refreshV510(){try{Q('#whatNowResult').innerHTML='<p>جارٍ التحليل…</p>';const d=await loadPortfolioData();if(!d)return;syncView(d);riskView(d);nowView(d);historyView(d);}catch(e){console.error(e);Q('#whatNowResult').innerHTML=`<p class="down">${e.message}</p>`;}}
function initMobileNav(){document.querySelectorAll('.mobile-bottom-nav button').forEach(b=>b.onclick=()=>document.querySelector(`.main-nav button[data-page="${b.dataset.page}"]`)?.click());}
async function init(){await initClient();Q('#whatNowBtn')?.addEventListener('click',refreshV510);Q('#portfolioSyncRefresh')?.addEventListener('click',refreshV510);initMobileNav();await refreshV510();setInterval(refreshV510,120000);}document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();